title: Andy the Cheese
description: A whimsical journey through curds, culture, and code
author: Andy
theme: jekyll-theme-cayman
baseurl: "" # Leave empty for GitHub Pages root
url: "https://andythecheese.github.io"
permalink: pretty
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Version tracking
version: 1.1.0
