title: Andy the Cheese
description: A whimsical journey through curds, culture, and code
author: Andy
theme: minima
baseurl: "" # Leave this empty for GitHub Pages root
url: "https://andythecheese.github.io"
permalink: pretty
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Version tracking
version: 1.0.0
