name: "Initialize Blog Folders (June 2025 – Dec 2026)"

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  create-folders:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create blog folder structure
        run: |
          for year in 2025 2026; do
            if [ "$year" = "2025" ]; then
              months="june july august september october november december"
            else
              months="january february march april may june july august september october november december"
            fi

            for month in $months; do
              mkdir -p "blog/$year/$month"
              echo "Placeholder" > "blog/$year/$month/.gitkeep"
            done
          done

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add blog/
          git commit -m "Add blog folders for June 2025 through December 2026" || echo "Nothing to commit"
          git push
